import { VerticalBox, Slider } from "std-widgets.slint";

export component Image_Window inherits Window {
    in-out property <image> mon_image;
    no-frame: true;
    always-on-top: true;
    callback start-drag();
    width: self.preferred-width;
    height: self.preferred-height;
    title: "overlay-image";
    background: transparent;

    VerticalBox {
        padding: 0px;
        spacing: 0px;
        Image {
            opacity: 50%;
            source: root.mon_image;
            width: self.preferred-width;
            height: self.preferred-height;
        }
    }

    TouchArea {

        width: 100%;
        height: 100%;
        pointer-event(event) => {
            if (event.kind == PointerEventKind.down) {
                root.start-drag();
            }
        }
    }
}


struct row {
    label: string,
    point: string,
    value: string,
}
export component AppWindows2 inherits Window {
    in-out property <image> mon_image;
    in-out property <string> HEXA;
    in-out property <string> HSL;
    in-out property <string> HSV;
    in-out property <string> RGB;
    in-out property <float> Transparence : 10;
    callback transparence-changed(value : int);
    width: 1200px;
    height: 500px;
    title: "overlay-settings";

    HorizontalLayout {
        Rectangle {
            width: 1200px;
            height: 500px;
            
            Image {
                source: root.mon_image;
                width: 624px;
                height: 351px;
                x: 500px;
                y: 75px;
            }
            Rectangle { 
                width: 480px;
                height: 370px;
                x: 70px;
                y: 65px;
                property <[row]> rows: [
                    { label: "Code Hexa", point: ":", value: root.HEXA },
                    { label: "Code HSL", point: ":", value: root.HSL },
                    { label: "Code HSV", point: ":", value: root.HSV },
                    { label: "Code RGB", point: ":", value: root.RGB },
                    { label: "Afficher image", point: ":"},
                    { label: "Bloquer image", point: ":"},
                    { label: "Transparence", point: ":", value: root.Transparence },
                ];

                for row[index] in rows : Rectangle {
                    Text {
                        font-size: 1.2rem;
                        height: 38px;
                        text: row.label;
                        x: 10px;
                        y: 20px + index * 45px;
                    }
                    Text {
                        font-size: 1.2rem;
                        height: 38px;
                        text: row.point;
                        x: 120px;
                        y: 20px + index * 45px;
                    }
                    Text {
                        font-size: 1.2rem;
                        height: 38px;
                        text: row.value;
                        x: 130px;
                        y: 20px + index * 45px;
                    }
                }
                Slider {
                    x: 160px;
                    y: 290px;
                    width: 150px;
                    minimum: 10;
                    maximum: 100;
                    value <=> root.Transparence;
                    changed => {
                        root.Transparence = Math.round(self.value);
                        root.transparence-changed(Math.round(self.value));
                    }
                }
            }
            
        }
    }
}