import { VerticalBox, Slider } from "std-widgets.slint";

export component Image_Window inherits Window {
    in-out property <image> mon_image;
    no-frame: true;
    always-on-top: true;
    callback start-drag();
    width: self.preferred-width;
    height: self.preferred-height;
    title: "overlay-image";

    VerticalBox {
        padding: 0px;
        spacing: 0px;
        Image {
            source: root.mon_image;
            width: self.preferred-width;
            height: self.preferred-height;
        }
    }

    TouchArea {

        width: 100%;
        height: 100%;
        pointer-event(event) => {
            if (event.kind == PointerEventKind.down) {
                root.start-drag();
            }
        }
    }
}

export component AppWindows2 inherits Window {
    in-out property <image> mon_image;
    width: 1200px;
    height: 500px;
    title: "overlay-settings";

    HorizontalLayout {
        Rectangle {
            width: 1200px;
            height: 500px;
            
            Image {
                source: root.mon_image;
                width: 624px;
                height: 351px;
                x: 500px;
                y: 75px;
            }
            Rectangle { 
                width: 480px;
                height: 370px;
                x: 70px;
                y: 65px;
                Text {
                    font-size: 1.2rem;
                    height: 31px;
                    text: "Code hexa           : ";
                    x: 10px;
                    y: 20px;
                }
                Text {
                    font-size: 1.2rem;
                    height: 38px;
                    text: "Code HSL             :";
                    x: 10px;
                    y: 65px;
                }
                Text {
                    font-size: 1.2rem;
                    height: 38px;
                    text: "Code RGB            :";
                    x: 10px;
                    y: 110px;
                }
                Text {
                    font-size: 1.2rem;
                    height: 38px;
                    text: "Code HSV            :";
                    x: 10px;
                    y: 155px;
                }
                Text {
                    font-size: 1.2rem;
                    height: 38px;
                    text: "Afficher image   :";
                    x: 10px;
                    y: 200px;
                }
                Text {
                    font-size: 1.2rem;
                    height: 38px;
                    text: "Bloquer image   :";
                    x: 10px;
                    y: 245px;
                }
                Text {
                    font-size: 1.2rem;
                    height: 38px;
                    text: "Transparence     :";
                    x: 10px;
                    y: 290px;
                }
                Slider {
                    x: 130px;
                    y: 290px;
                    width: 150px;
                    minimum: 0;
                    value: 50;
                    maximum: 100;
                }
                Text {
                    font-size: 1.2rem;
                    height: 38px;
                    text: "%";
                    x: 300px;
                    y: 290px;
                }
            }
            
        }
    }
}